spring:
  datasource:
    # jdbc
    #    password: kDEcCmV6+nTWVWL5BmNhCRqfdeeLFi50ze1a4Bg8VccQ8ixGS10XhTlWtw6V/3T3EcjILjb3Wkvax3H+e0G7bg==
    username: root
    url: jdbc:mysql:///activiti?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    password: root
    #durid 连接池
    druid:
      # 配置 connection-properties，启用加密，配置公钥。
      #      connection-properties: clientEncoding=UTF-8;config.decrypt=true;config.decrypt.key=${project.druid-public-key}
      #统计stat,sql防火墙wall,config启用加密等
      filter:
        config:
          # 启动ConfigFilter
          enabled: true
        stat:
          enabled: true
          log-slow-sql: true
        wall:
          ## 不允许的语句 ##
          config:
            alter-table-allow: false
            create-table-allow: false
            drop-table-allow: false
            intersect-allow: false
            # MINUS INTERSECT
            minus-allow: false
            # SELECT *
            select-all-column-allow: true
            truncate-allow: false
          enabled: true
          log-violation: true
          throw-exception: false
      filters: stat,wall,config
      #初始化连接大小
      initial-size: 10
      #最大连接数
      max-active: 100
      #获取连接最大等待时间
      max-wait: 10000
      #最小空闲
      min-idle: 3
      #自动清除无用连接
      remove-abandoned: true
      #清除无用连接的等待时间
      remove-abandoned-timeout: 180
      stat-view-servlet:
        login-password: admin
        login-username: admin
        reset-enable: false
      #连接属性
      #spring.datasource.druid.pool-prepared-statements=
      #spring.datasource.druid.max-pool-prepared-statement-per-connection-size=
      #和上面的等价
      #spring.datasource.druid.max-open-prepared-statements=
      #spring.datasource.druid.validation-query=
      #spring.datasource.druid.validation-query-timeout=
      #spring.datasource.druid.test-on-borrow=
      #spring.datasource.druid.test-on-return=
      #spring.datasource.druid.test-while-idle=
      #spring.datasource.druid.time-between-eviction-runs-millis=
      #spring.datasource.druid.min-evictable-idle-time-millis=
      #spring.datasource.druid.max-evictable-idle-time-millis=
  mvc:
    # 设定静态文件路径，js,css等
    static-path-pattern: /static/**
  # redis
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 10
        # 连接池最大空闲连接数
        max-idle: 10
    password:
    port: 6379
    #连接超时时间(毫秒)
    timeout: 0
  servlet:
    multipart:
      # 上传大小限制
      max-file-size: 1024MB
      max-request-size: 1024MB
  task:
    scheduling:
      pool:
        #定时任务池容量
        size: 10
      #定时任务池名称前缀
      thread-name-prefix: scheduling-

#cache
#spring.cache.cache-names=ehcache,redis
#spring.cache.ehcache.config=classpath*:cache/ehcache.xml
#
#shiro.enabled=true
#shiro.annotations.enabled=true

#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#freemarker
# 模板路径配置，多个模板路径用分号分割
#spring.freemarker.template-loader-path=classpath:/templates/


#project 项目相关配置
project:
  contact-email: gl@110.com
  contact-name: green
  contact-url: http://www.greelee.com
  description: web-demo
  ehcache-classpath: cache/ehcache.xml
  enable-swagger: true
  terms-of-service-url: http://192.168.1.3:${server.port}
  version: 1.0
  # 登录有效期
  session-timeout: 3600000
  # Druid加密公钥
#  druid-public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKzW/uRgE61ZMFTViMjkJT2v67d4WJ/1UluAbqh/0E28Ji3EBCMxBKm0Ib3iN0TqguDuMbD3FHMOOiCDS28JBdUCAwEAAQ==

sys:
  auth:
    admin-name: gelin
    admin-password: gelin
    audience: web-demo
    jwt-time-to-live: ${project.session-timeout}

  log:
    write-to-data-base: true
#  upload:
#    # 上传文件系统目录
#    upload-file-dir: D:/resource/f
#    # 上传文件访问地址前缀
#    upload-file-url: http://192.168.0.178:9090/f

# 日志
logging:
  file: log/log.log
  level:
    com:
      sysmain: debug
    root: info

server:
  port: 8080

